bentoml/OpenLLM

- README.md
- pyproject.toml
- src/openllm/cli.py
- src/openllm/client.py
Set host to localhost and update project metadata
> chore: metadata

- src/openllm/cli.py
> refactor: toplevel CLI

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- changelog.d/27.feature.md
- changelog.d/28.change.md
- src/openllm/__init__.py
- src/openllm/_configuration.py
- src/openllm/_llm.py
- src/openllm/_package.py
- src/openllm/_service.py
- src/openllm/cli.py
- src/openllm/models/auto/factory.py
- src/openllm/models/chatglm/modeling_chatglm.py
- src/openllm/models/dolly_v2/modeling_dolly_v2.py
- src/openllm/models/flan_t5/modeling_flan_t5.py
- src/openllm/models/opt/modeling_opt.py
- src/openllm/models/starcoder/modeling_starcoder.py
- src/openllm/utils/__init__.py
- src/openllm/utils/dantic.py
- src/openllm/utils/import_utils.py
- src/openllm/utils/lazy.py
- src/openllm_client/_prompt.py
- src/openllm_client/runtimes/base.py
- tests/test_configuration.py
update changelog notes
faster CLI loaded time
> perf: build quantization and better transformer behaviour

- changelog.d/37.change.md
- src/openllm/cli.py
> fix: agent log

- src/openllm/cli.py
> chore(cli): normalize kebab case

- src/openllm/_configuration.py
- tests/test_configuration.py
> feat(config): allow to generate new class and overwrite default config

- src/openllm/cli.py
> chore(cli): better command recommendation

- changelog.d/52.feature.md
- changelog.d/58.fix.md
- pyproject.toml
- src/openllm/_configuration.py
- src/openllm/_llm.py
- src/openllm/_package.py
- src/openllm/cli.py
- src/openllm/models/auto/configuration_auto.py
- src/openllm/utils/__init__.py
- src/openllm/utils/import_utils.py
- src/openllm/utils/lazy.py
- src/openllm_client/_prompt.py
- tests/_strategies/_configuration.py
> fix(cli): ensure we parse tag for download

- .github/workflows/auto-bot.yml
- src/openllm/_llm.py
- src/openllm/_strategies.py
- tests/test_strategies.py
- tests/test_strategy.py
- typings/rsmiBindings.pyi
A custom strategies that brings support for AMD GPU (experimental)
Address #65
> feat: cascading resource strategies

- .github/workflows/binary-releases.yml
> fix: binary should release on tag not dev

- src/openllm/_configuration.py
> feat: dict() protocol

- examples/bentoml-demo/service.py
- examples/langchain-chains-demo/service.py
- pyproject.toml
- src/openllm/_llm.py
> fix(load): tokenizer and adapter within a BentoLLM

- pyproject.toml
- tests/test_client.py
> tests: add sanity check for openllm.client

- .github/workflows/ci.yml
- pyproject.toml
- src/openllm/_package.py
- src/openllm/_service.py
- src/openllm/cli.py
- tests/test_package.py
> feat: custom dockerfile templates

- CITATION.cff
- README.md
> feat: add citation

- src/openllm/models/falcon/modeling_falcon.py
- src/openllm/models/mpt/configuration_mpt.py
- src/openllm/models/mpt/modeling_mpt.py
- src/openllm_client/runtimes/base.py
> chore: fix mpt loading on single GPU

- .pre-commit-config.yaml
- README.md
- changelog.d/115.feature.md
- nightly-requirements.txt
- pyproject.toml
- src/openllm/__init__.py
- src/openllm/models/__init__.py
- src/openllm/models/auto/configuration_auto.py
- src/openllm/models/auto/modeling_auto.py
- src/openllm/models/baichuan/__init__.py
- src/openllm/models/baichuan/configuration_baichuan.py
- src/openllm/models/baichuan/modeling_baichuan.py
- src/openllm/serialisation/constants.py
- src/openllm/serialisation/transformers.py
- src/openllm/utils/dummy_pt_objects.py
- tests/conftest.py
- tests/models_test.py
- tools/dependencies.py
- tools/typings
The baichuan-7B is a widely-spread open-source model, I'd like to integrate it with OpenLLM.
Baichuan Introduction
https://github.com/baichuan-inc/Baichuan-7B/blob/main/README_EN.md
HuggingFace Link
https://huggingface.co/baichuan-inc/Baichuan-7B
> feat(models): Baichuan

- .github/workflows/binary-releases.yml
- README.md
- src/openllm/models/llama/configuration_llama.py
- src/openllm/models/llama/modeling_llama.py
- tests/configuration_test.py
- tests/models_test.py
- tests/strategies_test.py
- tools/pyright
- tools/update-readme.py
> fix(ci): add configuration for running llama

- src/openllm/_llm.py
- src/openllm/cli.py
- src/openllm/models/llama/__init__.py
- src/openllm/models/llama/configuration_llama.py
- src/openllm/models/mpt/__init__.py
- src/openllm/models/mpt/configuration_mpt.py
- src/openllm/utils/import_utils.py
> feat: revision parsed via model_id

- changelog.d/130.feature.md
- src/openllm/cli.py
- src/openllm/models/llama/modeling_llama.py
- src/openllm/playground/llama2_qlora.py
- src/openllm/utils/dantic.py
> feat(cli): query with per request instruction

- changelog.d/132.breaking.md
- src/openllm/_llm.py
- src/openllm/models/baichuan/modeling_baichuan.py
- src/openllm/models/chatglm/modeling_chatglm.py
- src/openllm/models/dolly_v2/modeling_dolly_v2.py
- src/openllm/models/falcon/modeling_falcon.py
- src/openllm/models/flan_t5/modeling_flan_t5.py
- src/openllm/models/gpt_neox/modeling_gpt_neox.py
- src/openllm/models/llama/modeling_llama.py
- src/openllm/models/llama/modeling_vllm_llama.py
- src/openllm/models/mpt/modeling_mpt.py
- src/openllm/models/opt/modeling_opt.py
- src/openllm/models/stablelm/modeling_stablelm.py
- src/openllm/models/starcoder/modeling_starcoder.py
- src/openllm/serialisation/__init__.py
- src/openllm/serialisation/ggml.py
- src/openllm/serialisation/transformers.py
Refactor on some of the internal logics for determining function
> perf(serialisation): implement wrapper to reduce callstack

- .github/workflows/binary-releases.yml
- .github/workflows/create-releases.yml
- tests/_strategies/_configuration.py
> ci: release python earlier than building binary wheels

- README.md
- changelog.d/146.feature.md
- src/openllm/_service.py
- src/openllm/_strategies.py
- src/openllm/cli.py
- src/openllm_client/runtimes/base.py
- src/openllm_client/runtimes/http.py
> feat(client): embeddings

- .pre-commit-config.yaml
> fix: disable auto fixes

- .github/workflows/release-notes.yml
> chore(release): add darwin binary to release notes

- .github/workflows/build.yml
- changelog.d/template.md.jinja
> fix(ci): Correctly set signing for pushing container images

- .github/workflows/build.yml
- CHANGELOG.md
- README.md
> infra: update changelog and added readme [generated] [skip ci]

- .github/actions/create_release_and_archive.sh
- .github/workflows/build.yml
- changelog.d/169.feature.md
> infra: add instruction for using docker images from release notes

- src/openllm/__init__.py
- src/openllm/_service.py
> chore(bnb): filter warnings message on CPU

- .github/workflows/binary-releases.yml
- .github/workflows/build.yml
- .github/workflows/create-releases.yml
- src/openllm/bundle/_package.py
Allow EC2 to also be called via workflow_dispatch
> fix: pattern matching for Windows openllm binary [skip ci]

- pyproject.toml
- src/openllm/__init__.py
- src/openllm/_configuration.py
- src/openllm/_llm.py
- src/openllm/_quantisation.py
- src/openllm/_schema.py
- src/openllm/bundle/oci/Dockerfile
- src/openllm/models/auto/configuration_auto.py
- src/openllm/models/auto/modeling_vllm_auto.py
- src/openllm/models/baichuan/__init__.py
- src/openllm/models/baichuan/modeling_vllm_baichuan.py
- src/openllm/models/dolly_v2/__init__.py
- src/openllm/models/dolly_v2/modeling_dolly_v2.py
- src/openllm/models/dolly_v2/modeling_vllm_dolly_v2.py
- src/openllm/models/gpt_neox/__init__.py
- src/openllm/models/gpt_neox/modeling_vllm_gpt_neox.py
- src/openllm/models/mpt/__init__.py
- src/openllm/models/mpt/modeling_vllm_mpt.py
- src/openllm/models/stablelm/__init__.py
- src/openllm/models/stablelm/modeling_vllm_stablelm.py
- src/openllm/models/starcoder/__init__.py
- src/openllm/models/starcoder/configuration_starcoder.py
- src/openllm/models/starcoder/modeling_starcoder.py
- src/openllm/models/starcoder/modeling_vllm_starcoder.py
- src/openllm/serialisation/__init__.py
- src/openllm/serialisation/transformers.py
- src/openllm/utils/dummy_vllm_objects.py
- src/openllm_client/runtimes/base.py
- tests/configuration_test.py
- chore(vllm): add all vllm supported models
- chore: update imports correct ruff
> chore(vllm): add all vLLM supported models

- changelog.d/183.feature.md
- src/openllm/_llm.py
- src/openllm/cli/entrypoint.py
- src/openllm/models/dolly_v2/modeling_dolly_v2.py
- src/openllm/models/mpt/modeling_mpt.py
- src/openllm/models/opt/modeling_flax_opt.py
- src/openllm/models/opt/modeling_opt.py
- src/openllm/models/opt/modeling_tf_opt.py
- src/openllm/models/starcoder/modeling_starcoder.py
- src/openllm/serialisation/__init__.py
- src/openllm/serialisation/constants.py
- src/openllm/serialisation/transformers/__init__.py
- src/openllm/serialisation/transformers/_helpers.py
- src/openllm/serialisation/transformers/weights.py
- src/openllm/utils/__init__.py
- src/openllm/utils/analytics.py
> feat: optimize model saving and loading on single GPU

- changelog.d/185.change.md
- src/openllm/_llm.py
- src/openllm/bundle/oci/Dockerfile
- src/openllm/cli/_factory.py
- src/openllm/models/llama/modeling_llama.py
- src/openllm/serialisation/transformers/__init__.py
- fix: enable xformers compiling from source for supporting torch version
- fix: install xformers for vllm ray runner
- fix: invalid attribute in llm_config
- fix: more explicit error when initialising vllm
- fix: checking intialisation after model conversion
> fix(models): setup xformers in base container and loading PyTorch meta weights

- .github/workflows/binary-releases.yml
- .github/workflows/build.yml
- src/openllm/__init__.py
- src/openllm/_configuration.py
- src/openllm/_generation.py
- src/openllm/_llm.py
- src/openllm/bundle/oci/Dockerfile
- src/openllm/models/falcon/modeling_falcon.py
- src/openllm/models/gpt_neox/modeling_gpt_neox.py
- src/openllm/models/llama/configuration_llama.py
- src/openllm/models/llama/modeling_llama.py
- src/openllm/models/stablelm/modeling_stablelm.py
- src/openllm/models/starcoder/modeling_starcoder.py
- src/openllm/serialisation/__init__.py
- src/openllm/serialisation/transformers/_helpers.py
- src/openllm/serialisation/transformers/weights.py
- tools/update-config-stubs.py
- init --wip--
- chore(generation): initial work for generating tokens
> infra(generation): initial work for generating tokens

- src/openllm/_llm.py
- src/openllm/cli/entrypoint.py
- chore: print stack when DEBUG is enabled
- chore: remove force push
> feat: --force-push to allow force push to bentocloud

- changelog.d/189.change.md
- src/openllm/_strategies.py
- src/openllm/bundle/_package.py
- tests/strategies_test.py
> feat(strategy): only spawn up one runner

- .gitattributes
- .github/workflows/compile-pypi.yml
- .github/workflows/create-releases.yml
- .github/workflows/release-notes.yml
- Formula/openllm.rb
- fix(ci): fix correct target path for release wheels
- infra: update brew tap to 0.2.18 release [generated] [skip ci]
> fix: release compiled wheels and 0.2.18 tap

- pyproject.toml
> fix(release): fix exclude options within compiled wheels

- .github/workflows/create-releases.yml
> chore(ci): ignore locking main action for release [skip ci]

- .github/workflows/ci.yml
- .github/workflows/compile-pypi.yml
- contrib/clojure/README.md
- hatch.toml
- hatch_build.py
- openllm-python/.python-version-default
- openllm-python/pyproject.toml
- pyproject.toml
- fix(ci): run push nightly wheels
- fix(ci): change default directory to run under subdir
> fix(ci): remove broken build hooks

- .github/dependabot.yml
- .github/workflows/compile-pypi.yml
- openllm-python/src/openllm/bundle/oci/Dockerfile
> chore(ci): add dependabot and fix vllm release container

- changelog.d/223.feature.md
- openllm-python/src/openllm/__init__.py
- openllm-python/src/openllm/models/auto/modeling_vllm_auto.py
- openllm-python/src/openllm/models/falcon/__init__.py
- openllm-python/src/openllm/models/falcon/configuration_falcon.py
- openllm-python/src/openllm/models/falcon/modeling_vllm_falcon.py
- openllm-python/src/openllm/utils/dummy_vllm_objects.py
> feat(models): add vLLM support for Falcon

- .github/README.md
- .github/workflows/binary-releases.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/cleanup.yml
- .github/workflows/clojure-frontend.yml
- .github/workflows/compile-pypi.yml
- .github/workflows/cron.yml
- .github/workflows/release-notes.yml
- DEVELOPMENT.md
- tools/lock-actions.sh
- tools/update-actions.sh
> chore: conditional commit for running jobs

- changelog.d/240.feature.md
- openllm-python/src/openllm/_generation.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_service.py
- openllm-python/src/openllm/_typing_compat.py
- openllm-python/src/openllm/models/llama/modeling_llama.py
- openllm-python/src/openllm/serialisation/transformers/__init__.py
- pyproject.toml
> feat: token streaming and SSE support

- .github/workflows/build-embedding.yml
- .github/workflows/build.yml
> feat(embeddings): Using self-hosted CPU EC2 runner

- .pre-commit-config.yaml
- changelog.d/260.feature.md
- openllm-core/src/openllm_core/_typing_compat.py
- openllm-core/src/openllm_core/utils/__init__.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_service.py
- tools/pyright
> feat(vllm): streaming

- openllm-python/src/openllm/_assign.py
- openllm-python/src/openllm/serialisation/transformers/weights.py
- chore(weights): ignore gguf pattern for non GGML backend
- chore: correct fix num_gpus to be divisble by 2
> fix(serving): vllm distributed size

- changelog.d/297.refactor.md
- openllm-client/pyproject.toml
- openllm-client/src/openllm_client/_base.py
- openllm-core/pyproject.toml
- openllm-core/src/openllm_core/_typing_compat.py
- openllm-core/src/openllm_core/utils/__init__.py
- openllm-core/src/openllm_core/utils/import_utils.py
- openllm-python/pyproject.toml
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_quantisation.py
- openllm-python/src/openllm/_service.py
- openllm-python/src/openllm/bundle/_package.py
- openllm-python/src/openllm/cli/_factory.py
- openllm-python/src/openllm/cli/_sdk.py
- openllm-python/src/openllm/cli/entrypoint.py
- openllm-python/src/openllm/models/auto/factory.py
- openllm-python/src/openllm/serialisation/__init__.py
- openllm-python/src/openllm/serialisation/transformers/__init__.py
- openllm-python/src/openllm/serialisation/transformers/_helpers.py
- openllm-python/src/openllm/testing.py
- openllm-python/src/openllm/utils/__init__.py
- openllm-python/tests/models/conftest.py
- tools/dependencies.py
- wip
- feat: GPTQ transformers integration
> fix(gptq): use upstream integration

- README.md
Update different sections of the readme to include latest features and reorg the "Supported models" section by using expandable menus.
> docs: Update the readme

- .github/workflows/compile-pypi.yml
- .github/workflows/create-releases.yml
- .github/workflows/release-notes.yml
- .pre-commit-config.yaml
- changelog.d/304.change.md
> revert: disable compiled wheels for now

- openllm-python/src/openllm/models/auto/__init__.py
- openllm-python/src/openllm/models/baichuan/__init__.py
- openllm-python/src/openllm/models/chatglm/__init__.py
- openllm-python/src/openllm/models/dolly_v2/__init__.py
- openllm-python/src/openllm/models/falcon/__init__.py
- openllm-python/src/openllm/models/gpt_neox/__init__.py
- openllm-python/src/openllm/models/llama/__init__.py
- openllm-python/src/openllm/models/mpt/__init__.py
- openllm-python/src/openllm/models/opt/__init__.py
- openllm-python/src/openllm/models/stablelm/__init__.py
- openllm-python/src/openllm/models/starcoder/__init__.py
> fix(prompt): correct export extra objects items

- bench.py
- changelog.d/375.feature.md
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_service.py
> feat: support continuous batching on `generate`

- openllm-core/src/openllm_core/utils/__init__.py
tested in https://colab.research.google.com/drive/1NLFaFNxNxVgLPVgRevGv3NeyzJadNw96#scrollTo=AQX6pOz8BEu3&uniqifier=7
just a feasible solution. Any idea about other alternatives ?
@aarnphm
> fix: asyncio stalling inside notebooks

- openllm-client/src/openllm_client/_base.py
- openllm-client/src/openllm_client/benmin/__init__.py
- openllm-client/src/openllm_client/benmin/_http.py
fixes an issue for https servers where the client would specifically attempt to use HTTP on port 443.
> fix: fix client HTTPS

- README.md
Add this tutorial in the OpenLLM readme for better visibility. cc @xianml
> docs: Add OpenLLM tutorial Google Colab link

- README.md
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/entrypoints/_openapi.py
- openllm-python/src/openllm/entrypoints/hf.py
- openllm-python/src/openllm/protocol/hf.py
> infra: update docs on serving fine-tuning layers

- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/bundle/_package.py
- openllm-python/src/openllm/bundle/oci/Dockerfile
- openllm-python/src/openllm/entrypoints/_openapi.py
- openllm-python/src/openllm/entrypoints/openai.py
> fix: update build dependencies and format chat prompt

- examples/bentoml-demo/service.py
- examples/langchain-chains-demo/service.py
- examples/langchain-tools-demo/service.py
- examples/openai_client.py
- examples/openllm-llama2-demo/openllm_llama2_demo.ipynb
> chore(examples): update openai client

- openllm-client/src/openllm_client/_http.py
> fix(client): one-shot generation construction

- openllm-core/src/openllm_core/_configuration.py
- openllm-core/src/openllm_core/_schemas.py
- openllm-core/src/openllm_core/utils/peft.py
- openllm-python/src/openllm/__init__.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_service.py
- openllm-python/src/openllm/_strategies.py
- ruff.toml
> chore(service): cleanup API

- .github/dependabot.yml
> infra: disable npm updates and correct python packages

- openllm-core/src/openllm_core/utils/__init__.py
- openllm-core/src/openllm_core/utils/dantic.py
- openllm-python/src/openllm/_runners.py
- openllm-python/src/openllm/bundle/_package.py
- openllm-python/src/openllm/bundle/oci/__init__.py
- openllm-python/src/openllm/utils/__init__.py
> fix: device imports using strategies

- openllm-python/src/openllm/_quantisation.py
> fix(gptq): update config fields

- examples/openai_completion_client.py
> fix: unbound variable for completion client

- openllm-core/src/openllm_core/utils/import_utils.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/bundle/oci/Dockerfile
- openllm-python/src/openllm/serialisation/transformers/__init__.py
- openllm-python/src/openllm/serialisation/transformers/_helpers.py
- openllm-python/tests/conftest.py
- tools/dependencies.py
- fix(awq): correct detection for awq
- chore: update base docker to work
> fix(awq): correct awq detection for support

- openllm-core/src/openllm_core/_typing_compat.py
- openllm-python/src/openllm/_runners.py
- openllm-python/src/openllm/serialisation/transformers/__init__.py
> feat(vllm): squeezellm

- README.md
> docs: update quantization notes

- openllm-python/src/openllm/cli/_factory.py
> fix(cli): append model-id instruction to build

- openllm-python/src/openllm/bundle/_package.py
- openllm-python/src/openllm/cli/_factory.py
- chore: update build message
- chore: add tracing dependencies to container
> container: update tracing dependencies

- openllm-python/src/openllm/_service.py
> revert: configuration not to dump flatten

- openllm-python/src/openllm/bundle/_package.py
> package: add openllm core dependencies to labels

- openllm-python/src/openllm/serialisation/__init__.py
> fix: correct importmodules locally

- openllm-core/src/openllm_core/_configuration.py
> fix: overload flattened dict

- openllm-client/src/openllm_client/_shim.py
> fix(client): check for should retry header

- openllm-client/src/openllm_client/_http.py
> chore(client): remove ununsed state enum

- openllm-client/src/openllm_client/_shim.py
> feat(client): support return response_cls to string

- changelog.d/615.feature.md
- openllm-client/src/openllm_client/__init__.pyi
- openllm-client/src/openllm_client/_http.py
- openllm-client/src/openllm_client/_schemas.py
- openllm-client/src/openllm_client/_typing_compat.py
> feat(client): add helpers subclass

- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_runners.py
- openllm-python/src/openllm/bundle/_package.py
- openllm-python/src/openllm/cli/entrypoint.py
- openllm-python/src/openllm/entrypoints/_openapi.py
- openllm-python/src/openllm/entrypoints/hf.py
- openllm-python/src/openllm/entrypoints/openai.py
- openllm-python/src/openllm/serialisation/transformers/__init__.py
> chore(llm): expose quantise and lazy load heavy imports

- changelog.d/618.feature.md
- openllm-core/src/openllm_core/_typing_compat.py
- openllm-core/src/openllm_core/utils/__init__.py
- openllm-python/src/openllm/_deprecated.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/cli/_sdk.py
- openllm-python/src/openllm/cli/entrypoint.py
- openllm-python/src/openllm/cli/termui.py
- openllm-python/src/openllm/utils/__init__.py
> feat(llm): update warning envvar and add embedded mode

- openllm-python/src/openllm_cli/entrypoint.py
> chore(cli): always show available models

- openllm-python/src/openllm_cli/_sdk.py
> fix(sdk): make sure build to quiet out stdout

- .pre-commit-config.yaml
- examples/openllm-llama2-demo/openllm_llama2_demo.ipynb
> chore: update jupyter notebooks with new API

- openllm-python/src/openllm_cli/entrypoint.py
> fix(cli): make sure to pass the dtype to subprocess service

- openllm-python/src/openllm/_llm.py
> fix(torch_dtype): load eagerly

- openllm-core/src/openllm_core/config/configuration_baichuan.py
- openllm-core/src/openllm_core/config/configuration_chatglm.py
- openllm-core/src/openllm_core/config/configuration_dolly_v2.py
- openllm-core/src/openllm_core/config/configuration_falcon.py
- openllm-core/src/openllm_core/config/configuration_flan_t5.py
- openllm-core/src/openllm_core/config/configuration_gpt_neox.py
- openllm-core/src/openllm_core/config/configuration_llama.py
- openllm-core/src/openllm_core/config/configuration_mistral.py
- openllm-core/src/openllm_core/config/configuration_mpt.py
- openllm-core/src/openllm_core/config/configuration_opt.py
- openllm-core/src/openllm_core/config/configuration_stablelm.py
- openllm-core/src/openllm_core/config/configuration_starcoder.py
This is a noop and not being used anywhere.
> infra: remove unused postprocess_generate

- openllm-client/src/openllm_client/_http.py
- openllm-client/src/openllm_client/_shim.py
> fix(client): correct destructor the httpx object boht sync and async

- openllm-python/src/openllm/_llm.py
> fix(generation): compatibility dtype with CPU

- openllm-python/src/openllm/_llm.py
> fix(cpu): more verbose definition for dtype casting

- openllm-python/src/openllm/_service.py
> fix(service): to yield out correct JSON objects

- openllm-python/src/openllm_cli/_factory.py
> fix(cli): set default dtype to auto infer

- openllm-python/pyproject.toml
- tools/dependencies.py
> fix(dependencies): lock build < 1 for now

- openllm-python/src/openllm/entrypoints/_openapi.py
- openllm-python/src/openllm/entrypoints/cohere.py
> chore(openapi): unify inject param

- DEVELOPMENT.md
- openllm-core/src/openllm_core/utils/__init__.py
- openllm-python/src/openllm/bundle/oci/__init__.py
- openllm-python/src/openllm/entrypoints/cohere.py
- openllm-python/src/openllm/playground/falcon_tuned.py
- openllm-python/src/openllm/playground/llama2_qlora.py
- openllm-python/src/openllm/playground/opt_tuned.py
> refactor: use DEBUG env-var instead of OPENLLMDEVDEBUG

- openllm-python/src/openllm_cli/entrypoint.py
> fix(cli): update context name parsing correctly

- ADDING_NEW_MODEL.md
- openllm-core/src/openllm_core/config/__init__.py
- openllm-core/src/openllm_core/config/configuration_auto.py
- openllm-core/src/openllm_core/config/configuration_mistral.py
- openllm-core/src/openllm_core/config/configuration_yi.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/bundle/_package.py
- openllm-python/src/openllm_cli/entrypoint.py
> feat: Yi models

- openllm-python/src/openllm/bundle/_package.py
fix the issue when build 
introduced in #592
> fix: correct OPENLLM_DEV_BUILD check

- ADDING_NEW_MODEL.md
- README.md
- cz.py
- openllm-core/src/openllm_core/config/configuration_auto.py
- openllm-core/src/openllm_core/config/configuration_mistral.py
- openllm-python/README.md
- tools/update-readme.py
> infra: update scripts to run update readme automatically

- README.md
- openllm-python/README.md
- tools/update-readme.py
> chore: update requirements in README.md

- openllm-core/src/openllm_core/config/configuration_falcon.py
> fix(falcon): remove early_stopping default arguments

- openllm-python/src/openllm/_llm.py
> feat(llm): respect warnings environment for dtype warning

- openllm-python/pyproject.toml
- openllm-python/src/openllm/_llm.py
- tools/dependencies.py
> infra: makes huggingface-hub requirements on fine-tune

- README.md
- openllm-core/src/openllm_core/config/configuration_auto.py
- openllm-core/src/openllm_core/config/configuration_phi.py
- openllm-python/README.md
- openllm-python/src/openllm/__init__.pyi
- tools/update-readme.py
> feat(models): Phi 1.5

- README.md
- openllm-core/src/openllm_core/config/configuration_chatglm.py
- openllm-python/README.md
> fix(docs): chatglm support on vLLM

- openllm-python/src/openllm/serialisation/constants.py
- openllm-python/src/openllm/serialisation/transformers/_helpers.py
> chore(loading): include verbose warning about trust_remote_code

- .cbfmt.toml
- README.md
- openllm-python/README.md
> infra: update cbfmt options

- examples/bentoml-demo/service.py
> fix(examples): add support for streaming feature

- openllm-python/src/openllm_cli/entrypoint.py
> fix(build): correctly parse default env for container

- changelog.d/680.fix.md
- openllm-python/src/openllm/bundle/_package.py
- openllm-python/src/openllm_cli/entrypoint.py
> fix(env): correct format environment on docker

- openllm-python/src/openllm/bundle/_package.py
> fix(envvar): explicitly set NVIDIA_DRIVER_CAPABILITIES

- openllm-python/src/openllm/_llm.py
> fix(llm): remove unnecessary check

- .github/workflows/create-releases.yml
> fix(infra): prepare correct dependencies for release [skip ci]

- openllm-core/pyproject.toml
> fix(dependencies): ignore broken cattrs release

- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_llm.pyi
> fix(annotations): check library through find_spec

- changelog.d/692.feature.md
- openllm-core/src/openllm_core/_configuration.py
- openllm-core/src/openllm_core/_schemas.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_runners.py
- openllm-python/src/openllm/_runners.pyi
> feat: heuristics logprobs

- README.md
- changelog.d/695.change.md
- examples/bentofile.yaml
- openllm-python/README.md
- openllm-python/pyproject.toml
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/bundle/_package.py
- openllm-python/src/openllm/bundle/oci/Dockerfile
- openllm-python/src/openllm/bundle/oci/__init__.py
- tools/dependencies.py
> feat(vllm): bump to 0.2.2

- README.md
- openllm-python/README.md
> chore: update documentation about runtime

- changelog.d/698.feature.md
> chore: update changelog [skip ci]

- openllm-python/src/openllm/_llm.py
> fix(backend): correct use variable for backend when initialisation

- openllm-python/pyproject.toml
- tools/dependencies.py
> chore: update lower bound version of bentoml to avoid breakage

- openllm-python/src/openllm/_llm.py
> feat(generation): add support for eos_token_id

- openllm-core/src/openllm_core/__init__.py
- openllm-python/tests/configuration_test.py
> fix(ci): tests

- .ruff.toml
- openllm-core/src/openllm_core/utils/__init__.py
- openllm-python/src/openllm/__main__.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/serialisation/transformers/_helpers.py
- openllm-python/src/openllm_cli/entrypoint.py
Sorry but there are too much wasted spacing in `_llm.py`, and I'm unhappy and not productive anytime I look or want to do anything with it
> chore(logger): fix logger and streamline style

- openllm-core/src/openllm_core/_configuration.py
- openllm-core/src/openllm_core/_schemas.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_runners.py
- openllm-python/src/openllm/entrypoints/openai.py
- openllm-python/src/openllm/protocol/openai.py
- openllm-python/src/openllm_cli/entrypoint.py
> fix(openai): correct stop tokens and finish_reason state

- openllm-python/tests/configuration_test.py
- tools/run-release-action
> fix(infra): setup higher timer for building container images

- openllm-client/src/openllm_client/_utils.pyi
- openllm-core/src/openllm_core/utils/__init__.py
- openllm-core/src/openllm_core/utils/__init__.pyi
- openllm-core/src/openllm_core/utils/import_utils.py
- openllm-python/src/openllm/_runners.py
- openllm-python/src/openllm/serialisation/transformers/__init__.py
- openllm-python/src/openllm/utils.pyi
- openllm-python/src/openllm_cli/entrypoint.py
> chore: cleanup loader

- ADDING_NEW_MODEL.md
- README.md
- changelog.d/728.change.md
- openllm-core/src/openllm_core/config/configuration_auto.py
- openllm-core/src/openllm_core/config/configuration_baichuan.py
- openllm-python/README.md
- new constant `CONFIG_SUPPORTED_ARCHITECTURES_MAPPING` to allow configs to support multiple architectures
- doc update
> fix(baichuan): supported from baichuan 2 from now on.

- openllm-python/README.md
- openllm-python/src/openllm_cli/entrypoint.py
> chore: revert back previous backend support PyTorch

- openllm-python/src/openllm/entrypoints/openai.py
> fix(openai): logprobs when echo is enabled

- openllm-python/pyproject.toml
- openllm-python/src/openllm/_service.py
- openllm-python/src/openllm/bundle/_package.py
- openllm-python/src/openllm/entrypoints/_openapi.py
- openllm-python/src/openllm/protocol/openai.py
- tools/dependencies.py
> feat: mixtral support

- local.sh
> chore: running all script when installation

- openllm-core/src/openllm_core/config/configuration_mixtral.py
> fix(mixtral): correct chat templates to remove additional spacing

- openllm-python/src/openllm/serialisation/transformers/weights.py
> fix(mixtral): setup hack atm to load weights from pt specifically instead of safetensors

- changelog.d/779.fix.md
- openllm-python/src/openllm/_runners.py
> fix(logprobs): correct check logprobs

- openllm-core/src/openllm_core/config/configuration_mixtral.py
- openllm-python/pyproject.toml
- openllm-python/src/openllm/serialisation/transformers/weights.py
- tools/dependencies.py
> perf: upgrade mixtral to use expert parallelism

- openllm-python/src/openllm_cli/entrypoint.py
> fix(cli): avoid runtime `__origin__` check for older Python

- Dockerfile
- openllm-python/README.md
- openllm-python/pyproject.toml
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_runners.py
- openllm-python/src/openllm/serialisation/transformers/__init__.py
- tools/dependencies.py
- feat(vllm): GPTQ support passthrough
- chore: run scripts
> feat(vllm): support GPTQ with 0.2.6

- .github/workflows/binary-releases.yml
- .github/workflows/ci.yml
- .github/workflows/compile-pypi.yml
- .github/workflows/create-releases.yml
- .github/workflows/release-notes.yml
> fix(ci): lock to v3 iteration of `actions/artifacts` workflow

- openllm-python/README.md
> chore(script): run vendored scripts

- Dockerfile
- changelog.d/837.change.md
- openllm-python/README.md
- openllm-python/pyproject.toml
- tools/dependencies.py
> chore(deps): bump vllm to 0.2.7

- Dockerfile
> fix(dockerfile): conflict deps

- README.md
- openllm-python/README.md
There is a broken link the README, I've fixed it to a working one.
> docs: update README.md telemetry code link

- CITATION.cff
It looks like the space was not intentional. My sincere apologies if it was.
> docs: Possible fix in citation

- .github/workflows/create-releases.yml
- .pre-commit-config.yaml
- .ruff.toml
- src/openllm/__main__.py
- src/openllm/accelerator_spec.py
- src/openllm/analytic.py
- src/openllm/clean.py
- src/openllm/cloud.py
- src/openllm/common.py
- src/openllm/local.py
- src/openllm/model.py
- src/openllm/repo.py
- src/openllm/venv.py
> infra(style): automatically create release notes from tag

- src/openllm/cloud.py
> fix(cloud): respect user-set BENTOML_HOME

- src/openllm/venv.py
fix: https://github.com/bentoml/OpenLLM/issues/1129
> fix: respect Python version of bento

- README.md
> chore: update instructions for deploy with openllm

- README.md
- src/openllm/__main__.py
- src/openllm/cloud.py
> feat: support --env

- src/openllm/__main__.py
> feat: add support for search filter
