- .github/workflows/cleanup-cache.yml
- .pre-commit-config.yaml
- changelog.d/80.fix.md
- hatch.toml
- pyproject.toml
- src/openllm/_configuration.py
- src/openllm/_llm.py
- src/openllm/_package.py
- src/openllm/_service.py
- src/openllm/_strategies.py
- src/openllm/cli.py
- src/openllm/models/dolly_v2/configuration_dolly_v2.py
- src/openllm/models/falcon/modeling_falcon.py
- src/openllm/utils/codegen.py
- src/openllm/utils/dantic.py
- tests/models/__init__.py
- tests/models/conftest.py
- tests/models/flan_t5/test_modeling_flax_flan_t5.py
- tests/models/opt/test_modeling_flax_opt.py
- tests/test_strategies.py
- tools/add-license-headers
- tools/generate-coverage.py
- tools/update-config-stubs.py
- tools/update-optional-dependencies.py
- tools/update-readme.py
- tools/write-coverage-report.py
> feat(start): `openllm start bento`

- .github/workflows/create-releases.yml
Until I figure out a way to use ODCI, tokens it is
> ci: using tokens for publishing

- changelog.d/141.fix.md
- pyproject.toml
- src/openllm/_llm.py
- src/openllm/bundle/_package.py
- src/openllm/cli.py
- src/openllm/serialisation/__init__.py
- src/openllm/serialisation/transformers.py
> fix(build): running from container choosing models correctly

- src/openllm/bundle/__init__.py
- src/openllm/bundle/oci/__init__.py
- src/openllm/cli/ext/get_prompt.py
In case the commit is a [skip ci], then we don't build the image
> fix: nightly resolver for correct tag

- changelog.d/181.fix.md
- src/openllm/_configuration.py
- src/openllm/_llm.py
- src/openllm/_strategies.py
- src/openllm/bundle/_package.py
- src/openllm/bundle/oci/Dockerfile
- src/openllm/cli/_factory.py
- src/openllm/cli/entrypoint.py
- src/openllm/cli/termui.py
- src/openllm/models/auto/factory.py
- src/openllm/utils/__init__.py
- src/openllm/utils/import_utils.py
This inherently fix vLLM loading bug for incorrect model_id
We also include xformers from source since the latest stable xformers are too old, which will break vLLM workers.
> fix(vllm): correctly read env for EnvVarMixin

- .github/workflows/compile-pypi.yml
- changelog.d/215.feature.md
> chore: upload nightly wheels to test.pypi.org

- openllm-python/src/openllm/_assign.py
When using VLLM with a machine with 4 GPUs, `tensor_parallel_size` is set to 2 instead of 4.
It's because the line making sure `num_gpus` is divisible by 2 is not right.
If `dev` is 4, `dev // 2` is 2 and 2 is not equal to 0.
Using `ceil` is not right either, if `dev` is 5, `ceil(dev / 2)` is 3 whereas it should be 4.
This PR fixes both issues.
It makes sure `num_gpus` is always divisible by 2 while taking the maximum number of GPUs possible (if there are 7 GPUs, 6 GPUs are taken).
Related PR: https://github.com/bentoml/OpenLLM/pull/285
> fix(serving): vllm bad num_gpus

- changelog.d/324.fix.md
- openllm-python/pyproject.toml
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/models/falcon/modeling_falcon.py
- openllm-python/src/openllm/models/llama/modeling_llama.py
- openllm-python/src/openllm/models/starcoder/modeling_starcoder.py
- openllm-python/src/openllm/serialisation/transformers/__init__.py
- openllm-python/src/openllm/serialisation/transformers/weights.py
- openllm-python/src/openllm/utils/dummy_pt_objects.py
- openllm-python/src/openllm/utils/dummy_vllm_objects.py
- tools/dependencies.py
correctly set serialisation options
> fix(serialisation): vllm ignore

- openllm-core/src/openllm_core/_configuration.py
This is now inference arguments, instead of config
> fix(stop): stop is not available in config

- openllm-core/pyproject.toml
- openllm-core/src/openllm_core/_configuration.py
- openllm-core/src/openllm_core/utils/peft.py
- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm/_strategies.py
- openllm-python/src/openllm/cli/entrypoint.py
- openllm-python/tests/strategies_test.py
Strategies shouldn't be a part of openllm-core
> refactor(strategies): move logics into openllm-python

- openllm-core/src/openllm_core/_configuration.py
See https://docs.python.org/3.8/whatsnew/changelog.html and https://bugs.python.org/issue30486
> chore: no need compat workaround for setting cell_contents

- openllm-python/src/openllm_cli/entrypoint.py
> fix(cli): correct set working_dir

- openllm-python/src/openllm/_deprecated.py
Fix `TypeError` occured when using `openllm.Runner`
```
lc_llm = OpenLLM(model_name=model_name, model_id=model_id, embedded=False, **attrs)
File "/opt/conda/lib/python3.8/site-packages/langchain/llms/openllm.py", line 171, in __init__
runner = openllm.Runner(
File "/opt/conda/lib/python3.8/site-packages/openllm/_deprecated.py", line 58, in Runner
model_id = attrs.get('model_id', default=os.getenv('OPENLLM_MODEL_ID', llm_config['default_id']))
TypeError: get() takes no keyword arguments
```
> fix(runner): remove keyword args for attrs.get()

- .pre-commit-config.yaml
- openllm-core/src/openllm_core/_configuration.py
- tools/update-mypy.py
> fix: correct set item for attrs >23.1

- openllm-python/src/openllm/_llm.py
- openllm-python/src/openllm_cli/entrypoint.py
Users should be able to set the dtype during build, as we it doesn't effect start time
> fix(torch_dtype): correctly infer based on options

- tools/run-release-action
Seems like the release process for PyPI usually takes from 4-7 minutes
> infra: reduce wait time to around 7 mins

- openllm-core/src/openllm_core/_configuration.py
logprobs=0 still outputs logprobs for one generation
> fix(logprobs): explicitly set logprobs=None

- changelog.d/774.feature.md
- changelog.d/775.change.md
- openllm-python/src/openllm_cli/_factory.py
- openllm-python/src/openllm_cli/entrypoint.py
- openllm-python/src/openllm_cli/extension/list_models.py
> fix(cli): correct set arguments for `openllm import` and `openllm build`

- Dockerfile
- openllm-python/src/openllm/bundle/_package.py
We can let pytorch install it's own cuda runtime and save some duplicate spaces
> improv(package): use python slim base image and let pytorch install cuda

- openllm-python/src/openllm_cli/extension/list_models.py
Fixes a typo in the pydoc / cli help output
> chore: fix typo in list_models pydoc

- openllm-client/pyproject.toml
- openllm-core/pyproject.toml
- openllm-python/src/openllm/bundle/_package.py
For openllm 0.4 branch, we want to limit BentoML version to >=1.1.10,<1.2
> fix: limit BentoML version range

- openllm-client/src/openllm_client/_shim.py
Use annotated type from `typing_compat` instead for compatibility with Python 3.8.
> fix(compat): use annotated type from `typing_compat`
